version: '3.8'
networks:
  web:
    name: web
    external: true

services:
  api-thetiptop-dev:
    container_name: "fr.dsp.thetiptop.api-dev"
    image: registry.dsp-archiwebf22-at-sb-ms.fr/thetiptop/api-thetiptop-develop:latest
    restart: unless-stopped
    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-thetiptop-dev.rule=Host(`dev.api.dsp-archiwebf22-at-sb-ms.fr`)
      - traefik.http.routers.api-thetiptop-dev.entrypoints=websecure
      - traefik.http.services.api-thetiptop-dev.loadbalancer.server.port=8080
    networks:
      - web
