version: '3.8'
networks:
  web:
    name: web
    external: true

services:
  api-thetiptop-dev:
    container_name: "fr.dsp.thetiptop.api-release"
    image: registry.dsp-archiwebf22-at-sb-ms.fr/thetiptop/api-thetiptop-release:latest
    restart: unless-stopped
    environment:
      - 'SPRING_PROFILES_ACTIVE=stage'
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-thetiptop-stage.rule=Host(`release.api.dsp-archiwebf22-at-sb-ms.fr`)
      - traefik.http.routers.api-thetiptop-stage.entrypoints=websecure
      - traefik.http.services.api-thetiptop-stage.loadbalancer.server.port=8080
    networks:
      - web
      - thetiptop-api
    volumes:
      - "/var/log/thetiptop-api/staging:/var/log/thetiptop-api"
